### PR TITLE
Fix error handling

### PR DESCRIPTION
**Pull request by huumanoid**
1. Good API function should be only synchronous or only asynchronous.
Asynchronous means that callback will be called at least when the caller-function will be finished.

2. Take into consideration all the errors passed by request

### CODE REVIEW

**Comment by xSlOom** [comment]
Added your fix and updating the npm package when i'm at home.

**Comment by huumanoid** [comment]
If the point of this PR is unclear for you, feel free to ask.
It's easy to mess up with `setImmediate`, `process.nextTick` etc...

**Comment by xSlOom** [comment]
It's okay, I understand a bit. ;)

Thanks!

**Comment by xSlOom** [comment]
Version 1.0.3 released.

I might take a look later about this setImmediate thing.

**Pull request merged**
