### PR TITLE
Add getNewUser function

### PR DESCRIPTION
**Pull request by huumanoid**
Yeah, it seems that I have messed up with branches a bit!
I'm sorry! Please, accept #5 first!

### CODE REVIEW

**Comment by xSlOom** [comment]
I have noticed on your getNewUser function, you can't always get the auser3 page. I have always the "Service error" message.

What is wrong with it?

Plus; Version 1.0.5 has been released on npm.

**Comment by huumanoid** [comment]
If tests for this function are fine, then it means that xat returns something wrong instead of new user. I'll add this information in corresponding `Error` instance.

Tests works only for stubs, no real requests made.

But I've run `example.js` and `getNewUser` returns an appropriate result.

**Comment by huumanoid** [comment]
And yes, of course, thank you for this important report.

**Comment by xSlOom** [comment]
Oh right.

I haven't said, it wasn't working. I'm trying one time and after it returns the "Service error" for no reasons.. It's probably a problem on my side or something like that, idk.

**Comment by huumanoid** [comment]
If you are curious, try to check the actual body, returned by `request`. Let me know, what happens, please! Thank you for your help!

**Comment by xSlOom** [comment]
I have tested again the request on auser3; and it seems to work fine now .. I don't know what was wrong with that..

**Comment by huumanoid** [comment]
Yes, my friend. This `auser3` thing is weird. And I don't know is there something we can do about it. May be we should add `&t=newDate()` to query string. Cloudflare doesn't cache auser3 at all, but who knows...
I'm glad to know that it's is fine for you! Thank you!

**Comment by xSlOom** [comment]
Yeah, we should do that about this "&t=" thing. Flash chat is doing that too to fetch auser3 page.

But if it doesn't fix, just leave it like that, it's probably all xat fault and not our fault.

> Request URL:http://xat.com/web_gear/chat/auser3.php?u=0&k2=0&t=0.8762123053893447

**Pull request merged**
