### PR TITLE
Tests for getChatConnection

### PR DESCRIPTION
**Pull request by huumanoid**
Thank you for this function! It's really usable for someone who wants to create a bot. 
I think it's OK to rely on your web API there, at least if you are going to keep your service available.
Your API returns strange results for some corner cases. Check them out! What do you think? Should you fix it?

No more tests done by me! Try to do it by yourself. It's fun! And it's very important!!! Tests make out life better and easier.

### CODE REVIEW

**Comment by xSlOom** [comment]
Thank you for your updates.

Since I'm busy at work, i'll take a look at your changes tonight.

And what's wrong about my api?  Does it affects something?

**Edit:** Tried fastly your tests and I have some errors:

>  getRegname
>     ✓ should return regname of 42
>     ✓ should return regname of 110110 (396ms)
>     ✓ should fail on non-number arg
>     ✓ should fail when id doesn't exists (269ms)
>     ✓ shouldn't be synchronous
> 
>   getID
>     ✓ should return id of Xat
>     ✓ should return id of SlOom (245ms)
>     ✓ should fail when regname doesn't exists (267ms)
>     ✓ should be case insensitive for Xat (275ms)
>     ✓ should be case insensitive for SlOom (249ms)
> 
>   getChatInfo
>     ✓ should return info about group chat (443ms)
>     ✓ should return info about group xat123 (279ms)
>     ✓ should return info about group 123 (258ms)
>     ✓ should fetch appropriate info about just created group (164ms)
> 
>   getNewInfo
>     1) should return correct result when last power is lovetest
>     2) should pass this error to caller when request returns error
> 
>   getChatConnection
>     ✓ should return correct result when getting connection info of chat 123
>     ✓ should return result when interacting with remote API (479ms)
>     3) should return error when getting info about chat 20000000000
>     4) should return error when getting info about chat 2000000000000
>     ✓ should return error when getting info about chat 200000000000000000000 (165ms)
> 
> 
>   17 passing (4s)
>   4 failing
> 
>   1) getNewInfo should return correct result when last power is lovetest:
>      Uncaught AssertionError: [ 'lovetest' ] deepEqual 'lovetest'
>       at xatapi.getNewInfo (test/api.js:147:14)
>       at source/xat.js:107:4
>       at handler (source/test-helpers.js:21:54)
>       at getFile (test/api.js:136:9)
>       at fs.readFile (source/test-helpers.js:33:5)
>       at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
> 
>   2) getNewInfo should pass this error to caller when request returns error:
>      Uncaught TypeError: Cannot read property 'substr' of undefined
>       at source/xat.js:86:31
>       at handler (source/test-helpers.js:21:54)
>       at makeRequestStub (test/api.js:157:54)
>       at Immediate.setImmediate (source/test-helpers.js:21:22)
> 
>   3) getChatConnection should return error when getting info about chat 20000000000:
> 
>       Uncaught AssertionError: null != null
>       + expected - actual
> 
>       
>       at xatapi.getChatConnection (test/api.js:222:16)
>       at Request._callback (source/xat.js:146:16)
>       at Request.self.callback (node_modules/request/request.js:186:22)
>       at Request.<anonymous> (node_modules/request/request.js:1081:10)
>       at IncomingMessage.<anonymous> (node_modules/request/request.js:1001:12)
>       at endReadableNT (_stream_readable.js:974:12)
>       at _combinedTickCallback (internal/process/next_tick.js:74:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
> 
>   4) getChatConnection should return error when getting info about chat 2000000000000:
> 
>       Uncaught AssertionError: null != null
>       + expected - actual
> 
>       
>       at xatapi.getChatConnection (test/api.js:222:16)
>       at Request._callback (source/xat.js:146:16)
>       at Request.self.callback (node_modules/request/request.js:186:22)
>       at Request.<anonymous> (node_modules/request/request.js:1081:10)
>       at IncomingMessage.<anonymous> (node_modules/request/request.js:1001:12)
>       at endReadableNT (_stream_readable.js:974:12)
>       at _combinedTickCallback (internal/process/next_tick.js:74:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
>

**Comment by huumanoid** [comment]
In general, your API is pretty OK! Just some strange things happens:

https://api.illuxat.com/chatconnexion.php?roomid=2000000000000
returns empty array

https://api.illuxat.com/chatconnexion.php?roomid=20000000000
returns 
```json
{
    "id": 2147483647,
    "ip": "fwdelb03-1789285345.us-east-1.elb.amazonaws.com",
    "port": 10002,
    "ctout": 60
}
```

It is doesn't important at all, but this is strange.You may skip this tests if you think this is wontfix!
Just add `.skip` to erroneous `it`
```js
it.skip('Test case blah blah blah', () => {
  // code

**Comment by xSlOom** [comment]
Oh well. I might have to fix the API later or maybe in a few minutes. :smile: 

Thank you!

**Comment by xSlOom** [comment]
So the API is normally fixed.

**Pull request merged**
