### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by huumanoid**
Here comes the tests!

Thanks to tests, some issues has been detected and fixed.

To perform tests, run
```sh
npm run test
```

I've got several recomendations for you
### Use only spaces or only tabs
Keep tracking which indents you are actually using.
There are a lot of discusses about the best types of indentation (tabs, 2 spaces, 4 spaces etc...)
The general idea is that you can use whatever you want, but it's absolutely discouraging to mix two different types of indentations in one file!

### If something meaningful can't be assigned to value, you should prefer null instead of 'None', 'Not found' etc
Remember, it's actually a library, which intended to be used by programs, not by humans.
Let end-user programs decide how to handle `null`.
`null` is an universal thing which signals that there is no value.
Moreover, sometimes 'None' is an actual, meaningful value (for e.g. let's imagine that Background can be 'None'), there is no way to distinguish is Background is 'None' or there is no Background at all.

Among this things, everything is great, your code works good. Well done!

### CODE REVIEW

**Comment by huumanoid** [comment]
Also, this pull request fixes the package.
The package has been broken, it could be installed but it couldn't be imported using `require('xatapi')`.

**Comment by xSlOom** [comment]
Hi,

I checked fastly your tests file, can you tell me more about on how it works?

Because you are using the xat.js file, but if you use the npm package (xatlib), it works same.. And about the space issues, it's not my fault, but github, because on PHPSTORM, it looks fine.

I might take a better look tonight after my work, but for now, I merged your pull request.

Thanks.

Edit: 

Tested your code, and sounds to work fine. (Must see more later)

> getRegname
    ✓ should return regname of 42
    ✓ should return regname of 110110 (911ms)
    ✓ should fail on non-number arg
    ✓ should fail when id doesn't exists (265ms)

> getID
    ✓ should return id of Xat
    ✓ should return id of SlOom (295ms)
    ✓ should fail when regname doesn't exists (243ms)
    ✓ should be case insensitive for Xat (269ms)
    ✓ should be case insensitive for SlOom (264ms)

> getChatInfo
    ✓ should return info about group chat (268ms)
    ✓ should return info about group xat123 (252ms)
    ✓ should return info about group 123 (267ms)
    ✓ should fetch appropriate info about just created group (287ms)

**Comment by huumanoid** [comment]
Thank you for your review! I'm glad that tests work for you too!
Here come some answers.

### Tests
Take a look at https://mochajs.org!
Mochajs package contains a binary which parses .js test files in it's own way.
When you call 'describe' function, you actually declare a topic, a thread, a batch of tests. 
Every 'it' statement is actually a test case. 
If any exceptions are thrown in 'it' statement's callback and hasn't caught, it's treated as test failure. That's why I've added some assertions. Assertions comes from nodejs library. 
You may notice that every 'it' function receives callback with one argument: 'done'. If our tests were synchronous, there would no need to use 'done'. However, our tests are async, so we should let test engine know when test is completed successfully.

Important: tests are not parallel. Tests are launched one by one. When first is completed, the second begins, and so on.

### xatlib
> Because you are using the xat.js file, but if you use the npm package (xatlib), it works same..

Ok, I think I got it. Package is broken when lies in repository, but you will fix it every time you publish it at npm. That's ok i guess, but it's not convenient for tests.
Interesting thing: npm registry is not the only source for npm package manager. Every folder of your file system may be a package, and every remote (git?) repository too. So you can install a package by the following way:
```sh
npm install github:/xsloom/xatapi
```
Or even from folder!
```sh
npm install /path/to/xatapi
```

Sometimes it's freakin suitable for tests!
Sometimes package at github may contain important changes but it haven't been upload to npm.
I think it's a good idea to keep xatapi repository to be a package-like.

### Spaces
You are lucky that spaces and tabs looks OK in PHPSTORM. If you open someone else's code and they uses '2 spaces' and 'tabs' sometimes, probably it won't look OK for you.
In my text editor it's not OK. Of course, I can configure it so it would treat tab as 4 spaces.
The general idea is when you are mixing tabs and spaces, you may cause problems with reading of your code for everyone who has tab configuration different than yours.
It's not acceptable by every code style convention. You may consider this rule as a rule of etiquette. Every time you write code which will be read by someone else, you have to write readable code.

**Comment by xSlOom** [comment]
Thank you for your review.

> I think it's a good idea to keep xatapi repository to be a package-like.

Well, if it's good to keep xatapi, we will keep xatapi, and i'll delete xatlib from npm.
And about spaces, I understand. I didn't know, it would not be good for everyone... Sorry.

And about the functions on /source/xat.js, all are good or it needs to be improved again?

**Comment by huumanoid** [comment]
I don't mean you should name your package 'xatapi' and not 'xatlib', though it's good when package name equal to npm registry package name.
I mean it's preferable to keep package installable from your git repository. I've fixed entry point of package in package.json, so I can install it from github directly. That's it.

The only reasonable improvement remains: do not ignore `error` of callback passed to `request` package. If `error` is not null, call xatapi's callback with error passed in.

You've done a good job! Thank you! I'm glad I'm able to use this staff in my `xat-cli`.

**Comment by xSlOom** [comment]
I understand, i'll follow your advices to improve my stuff in the future.

And thank you for your feedback! I'm glad to have a positive feedback from someone more "professional" than me.

**Pull request merged**
